services:

  # Kafka Service
  kafka-service:
    env_file:
      - .env
    image: ${REGISTRY}/${IMAGE_NAME}-kafka-service:${TAG}
    container_name: next-mart-kafka-service-prod
    restart: unless-stopped
    ports:
      - "6009:6009"
    environment:
      NODE_ENV: development
      PORT: 6009
      KAFKA_API_KEY: ${KAFKA_API_KEY}
      KAFKA_API_SECRET: ${KAFKA_API_SECRET}
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - next-mart-network-prod

  # Auth Service
  auth-service:
    env_file:
      - .env
    image: ${REGISTRY}/${IMAGE_NAME}-auth-service:${TAG}
    container_name: next-mart-auth-service-prod
    restart: unless-stopped
    ports:
      - "6001:6001"
    environment:
      NODE_ENV: development
      PORT: 6001
      DATABASE_URL: ${DATABASE_URL}
      REDIS_DATABASE_URI: ${REDIS_DATABASE_URI}
    networks:
      - next-mart-network-prod

  # Product Service
  product-service:
    env_file:
      - .env
    image: ${REGISTRY}/${IMAGE_NAME}-product-service:${TAG}
    container_name: next-mart-product-service-prod
    restart: unless-stopped
    ports:
      - "6002:6002"
    environment:
      NODE_ENV: development
      PORT: 6002
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - next-mart-network-prod

  # Order Service
  order-service:
    env_file:
      - .env
    image: ${REGISTRY}/${IMAGE_NAME}-order-service:${TAG}
    container_name: next-mart-order-service-prod
    restart: unless-stopped
    ports:
      - "6003:6003"
    environment:
      NODE_ENV: development
      PORT: 6003
      DATABASE_URL: ${DATABASE_URL}
      REDIS_DATABASE_URI: ${REDIS_DATABASE_URI}
    networks:
      - next-mart-network-prod

  # Recommendation Service
  recommendation-service:
    env_file:
      - .env
    image: ${REGISTRY}/${IMAGE_NAME}-recommendation-service:${TAG}
    container_name: next-mart-recommendation-service-prod
    restart: unless-stopped
    ports:
      - "6007:6007"
    environment:
      NODE_ENV: development
      PORT: 6007
      DATABASE_URL: ${DATABASE_URL}
      KAFKA_API_KEY: ${KAFKA_API_KEY}
      KAFKA_API_SECRET: ${KAFKA_API_SECRET}
    depends_on:
      kafka-service:
        condition: service_started
    networks:
      - next-mart-network-prod

    # Admin Service
  admin-service:
    env_file:
      - .env
    image: ${REGISTRY}/${IMAGE_NAME}-admin-service:${TAG}
    container_name: next-mart-admin-service-prod
    restart: unless-stopped
    ports:
      - "6004:6004"
    environment:
      NODE_ENV: development
      PORT: 6004
      DATABASE_URL: ${DATABASE_URL}
      KAFKA_API_KEY: ${KAFKA_API_KEY}
      KAFKA_API_SECRET: ${KAFKA_API_SECRET}
    depends_on:
      kafka-service:
        condition: service_started
    networks:
      - next-mart-network-prod

  # chat Service
  chat-service:
    env_file:
      - .env
    image: ${REGISTRY}/${IMAGE_NAME}-chatting-service:${TAG}
    container_name: next-mart-chat-service-prod
    restart: unless-stopped
    ports:
      - "6005:6005"
    environment:
      NODE_ENV: development
      PORT: 6005
      DATABASE_URL: ${DATABASE_URL}
      KAFKA_API_KEY: ${KAFKA_API_KEY}
      KAFKA_API_SECRET: ${KAFKA_API_SECRET}
    depends_on:
      kafka-service:
        condition: service_started
    networks:
      - next-mart-network-prod

  # Logger Service
  logger-service:
    env_file:
      - .env
    image: ${REGISTRY}/${IMAGE_NAME}-logger-service:${TAG}
    container_name: next-mart-logger-service-prod
    restart: unless-stopped
    ports:
      - "6006:6006"
    environment:
      NODE_ENV: development
      PORT: 6006
      DATABASE_URL: ${DATABASE_URL}
      KAFKA_API_KEY: ${KAFKA_API_KEY}
      KAFKA_API_SECRET: ${KAFKA_API_SECRET}
    depends_on:
      kafka-service:
        condition: service_started
    networks:
      - next-mart-network-prod

  # Seller Service
  seller-service:
    env_file:
      - .env
    image: ${REGISTRY}/${IMAGE_NAME}-seller-service:${TAG}
    container_name: next-mart-seller-service-prod
    restart: unless-stopped
    ports:
      - "6008:6008"
    environment:
      NODE_ENV: development
      PORT: 6008
      DATABASE_URL: ${DATABASE_URL}
      KAFKA_API_KEY: ${KAFKA_API_KEY}
      KAFKA_API_SECRET: ${KAFKA_API_SECRET}
    depends_on:
      kafka-service:
        condition: service_started
    networks:
      - next-mart-network-prod


  # API Gateway
  api-gateway:
    env_file:
      - .env
    image: ${REGISTRY}/${IMAGE_NAME}-api-gateway:${TAG}
    container_name: next-mart-api-gateway-prod
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      PORT: 8080
    depends_on:
      auth-service:
        condition: service_started
      product-service:
        condition: service_started
      order-service:
        condition: service_started
      recommendation-service:
        condition: service_started
    networks:
      - next-mart-network-prod

  # User UI
  # user-ui:
  #   env_file:
  #     - .env
  #   build:
  #     context: .
  #     dockerfile: ./apps/user-ui/Dockerfile
  #   container_name: next-mart-user-ui-prod
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     NODE_ENV: development
  #     NEXT_PUBLIC_API_URL: http://api-gateway:8080
  #     DEBUG: "true"
  #   depends_on:
  #     api-gateway:
  #       condition: service_started
  #   networks:
  #     - next-mart-network-prod

  # # Seller UI
  # seller-ui:
  #   env_file:
  #     - .env
  #   build:
  #     context: .
  #     dockerfile: ./apps/seller-ui/Dockerfile
  #   container_name: next-mart-seller-ui-prod
  #   restart: unless-stopped
  #   ports:
  #     - "3001:3000"
  #   environment:
  #     NODE_ENV: development
  #     NEXT_PUBLIC_API_URL: http://api-gateway:8080
  #     DEBUG: "true"
  #   depends_on:
  #     api-gateway:
  #       condition: service_started
  #   networks:
  #     - next-mart-network-prod


networks:
  next-mart-network-prod:
    driver: bridge