export const navItems: NavItemTypes[] = [
  { title: 'Home', href: '/' },
  { title: 'Products', href: '/products' },
  { title: 'Shops', href: '/shops' },
  { title: 'Events', href: '/events' },
  { title: 'Become a Seller', href: '/become-seller' },
];

export const countries = [
  'Australia',
  'Austria',
  'Belgium',
  'Brazil',
  'Bulgaria',
  'Canada',
  'Chile',
  'Colombia',
  'Croatia',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Estonia',
  'Finland',
  'France',
  'Germany',
  'Gibraltar',
  'Greece',
  'Hong Kong',
  'Hungary',
  'India',
  'Ireland',
  'Italy',
  'Japan',
  'Latvia',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Malaysia',
  'Malta',
  'Mexico',
  'Netherlands',
  'New Zealand',
  'Norway',
  'Poland',
  'Portugal',
  'Romania',
  'Rwanda',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Spain',
  'Sweden',
  'Switzerland',
  'Thailand',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
];

export const categories = [
  { value: 'books', label: 'Books & Stationery' },
  { value: 'electronics', label: 'Electronics' },
  { value: 'fashion', label: 'Fashion' },
  { value: 'home', label: 'Home & Garden' },
  { value: 'beauty', label: 'Beauty & Personal Care' },
  { value: 'sports', label: 'Sports & Outdoors' },
  { value: 'toys', label: 'Toys & Games' },
  { value: 'automotive', label: 'Automotive' },
  { value: 'baby', label: 'Baby Products' },
  { value: 'computers', label: 'Computers & Accessories' },
  { value: 'grocery', label: 'Grocery & Gourmet Food' },
  { value: 'health', label: 'Health & Household' },
  { value: 'industrial', label: 'Industrial & Scientific' },
  { value: 'luggage', label: 'Luggage & Travel Gear' },
  { value: 'movies', label: 'Movies & TV' },
  { value: 'music', label: 'Music, CDs & Vinyl' },
  { value: 'office', label: 'Office Products' },
  { value: 'pet', label: 'Pet Supplies' },
  { value: 'software', label: 'Software' },
  { value: 'tools', label: 'Tools & Home Improvement' },
  { value: 'video_games', label: 'Video Games' },
  { value: 'appliances', label: 'Appliances' },
  { value: 'arts', label: 'Arts, Crafts & Sewing' },
  { value: 'cell_phones', label: 'Cell Phones & Accessories' },
  { value: 'collectibles', label: 'Collectibles & Fine Art' },
  { value: 'gift_cards', label: 'Gift Cards' },
  { value: 'handmade', label: 'Handmade Products' },
  { value: 'jewelry', label: 'Jewelry' },
  { value: 'musical_instruments', label: 'Musical Instruments' },
  { value: 'prime_pantry', label: 'Prime Pantry' },
  { value: 'shoes', label: 'Shoes & Handbags' },
  { value: 'watches', label: 'Watches' },
  { value: 'garden', label: 'Patio, Lawn & Garden' },
  { value: 'medical', label: 'Medical Supplies & Equipment' },
  { value: 'services', label: 'Home Services' },
  { value: 'renewed', label: 'Amazon Renewed' },
  { value: 'outdoors', label: 'Outdoor Recreation' },
  { value: 'subscriptions', label: 'Subscribe & Save' },
  { value: 'alcohol', label: 'Beer, Wine & Spirits' },
  { value: 'magazines', label: 'Magazine Subscriptions' },
  { value: 'lighting', label: 'Lighting & Ceiling Fans' },
  { value: 'security', label: 'Home Security & Surveillance' },
  { value: 'kitchen', label: 'Kitchen & Dining' },
  { value: 'bath', label: 'Bath' },
  { value: 'furniture', label: 'Furniture' },
  { value: 'crafts', label: 'Crafts & Hobbies' },
  { value: 'party', label: 'Party Supplies' },
  { value: 'costumes', label: 'Costumes & Accessories' },
  { value: 'personal_care', label: 'Personal Care Appliances' },
  { value: 'cleaning', label: 'Cleaning Supplies' },
  { value: 'storage', label: 'Storage & Organization' },
  { value: 'building_supplies', label: 'Building Supplies' },
  { value: 'hardware', label: 'Hardware' },
  { value: 'paint', label: 'Paint, Wall Treatments & Supplies' },
  { value: 'plumbing', label: 'Plumbing' },
  { value: 'electrical', label: 'Electrical' },
  { value: 'safety', label: 'Safety & Security' },
  { value: 'lab', label: 'Lab & Scientific Products' },
  { value: 'restaurant', label: 'Restaurant & Food Service' },
  { value: 'janitorial', label: 'Janitorial & Sanitation Supplies' },
  { value: 'education', label: 'Education Supplies' },
  { value: 'science', label: 'Science Education' },
  { value: 'diagnostic', label: 'Diagnostic & Screening' },
  { value: 'mobility', label: 'Mobility & Daily Living Aids' },
  { value: 'sexual_wellness', label: 'Sexual Wellness' },
  { value: 'erotic', label: 'Erotic Literature & Art' },
];
